[package]
name = "rust-play"
version = "0.1.0"
authors = ["Hamish Currie <hamish@currie.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
